name: TypeScript Check

on: [pull_request]

jobs:
  tsc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Authenticate with npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm login

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript compiler
        id: tsc
        run: |
          npx tsc --noEmit --pretty false > tsc_output.txt || true

      - name: Print TypeScript compiler output
        run: cat tsc_output.txt

      - name: Convert TypeScript errors to annotations
        run: |
          node .github/scripts/tsc-to-annotations.js
